name = "aws-worker"
main = "index.js"
compatibility_date = "2022-09-09"
node_compat = true

[vars]
AWS_REGION = "us-west-2"
AWS_DYNAMO_TABLE = "test_table_name"
AWS_DYNAMO_PRIMARYKEY = "test_primary_key"
AWS_AURORA_TABLE = "demo.friends"
AWS_AURORA_RESOURCE_ARN = "arn:aws:rds:<< FIXME >>"
